# Generated by Django 3.1 on 2020-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('directors', models.CharField(db_column='Directors', max_length=40)),
                ('stars', models.CharField(db_column='Stars', max_length=40)),
                ('category', models.CharField(db_column='Category', max_length=20)),
                ('year', models.CharField(db_column='Year', max_length=10)),
                ('rate', models.CharField(db_column='Rate', max_length=10)),
                ('runtime', models.CharField(db_column='Runtime', max_length=20)),
                ('imdb', models.CharField(db_column='IMDb', max_length=40)),
                ('ticket', models.CharField(db_column='Ticket', max_length=40)),
            ],
            options={
                'db_table': 'Movie',
                'managed': False,
            },
        ),
    ]
